### Welcome Message (Local)
GET http://localhost:3000/

### Get All Users (Local)
GET http://localhost:3000/users

### Get User 1 by ID (Local)
GET http://localhost:3000/users/68b9bd5633ab395eda5c2ef6

### Get User 2 by ID (Local)
GET http://localhost:3000/users/68b9bd7933ab395eda5c2ef8

### Get User 3 by ID (Local)
GET http://localhost:3000/users/68bab05fbff4f64d4a2cca68

### Create a New User (Local)
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Chinedu",
  "lastName": "Okoro",
  "email": "chinedu.okoro@example.com",
  "favoriteColor": "Purple",
  "birthday": "1988-03-12T00:00:00.000Z"
}

### Create Another User (Local)
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Promise",
  "lastName": "Ezenwoke",
  "email": "ezenwokeuchechukwu@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "1992-07-21T00:00:00.000Z"
}

### Update User 1 (Local)
PUT http://localhost:3000/users/68b9bd5633ab395eda5c2ef6
Content-Type: application/json

{
  "firstName": "Chinedu",
  "lastName": "Okoro-Updated",
  "email": "chinedu.updated@example.com",
  "favoriteColor": "Gold",
  "birthday": "1988-03-12T00:00:00.000Z"
}

### Delete User 3 (Local)
DELETE http://localhost:3000/users/68bab05fbff4f64d4a2cca68

---

### Welcome Message (Render)
GET https://cse-341-project01-isr0.onrender.com/

### Get All Users (Render)
GET https://cse-341-project01-isr0.onrender.com/users

### Get User 1 by ID (Render)
GET https://cse-341-project01-isr0.onrender.com/users/68b9bd5633ab395eda5c2ef6

### Get User 2 by ID (Render)
GET https://cse-341-project01-isr0.onrender.com/users/68b9bd7933ab395eda5c2ef8

### Get User 3 by ID (Render)
GET https://cse-341-project01-isr0.onrender.com/users/68bab05fbff4f64d4a2cca68

### Create a New User (Render)
POST https://cse-341-project01-isr0.onrender.com/users
Content-Type: application/json

{
  "firstName": "Chinedu",
  "lastName": "Okoro",
  "email": "chinedu.okoro@example.com",
  "favoriteColor": "Purple",
  "birthday": "1988-03-12T00:00:00.000Z"
}

### Update User 1 (Render)
PUT https://cse-341-project01-isr0.onrender.com/users/68b9bd5633ab395eda5c2ef6
Content-Type: application/json

{
  "firstName": "Chinedu",
  "lastName": "Okoro-Updated",
  "email": "chinedu.updated@example.com",
  "favoriteColor": "Gold",
  "birthday": "1988-03-12T00:00:00.000Z"
}

### Delete User 3 (Render)
DELETE https://cse-341-project01-isr0.onrender.com/users/68bab05fbff4f64d4a2cca68
